homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name='home'),
    path('comingsoon/', views.home2, name='home2'),
    path('story1/', views.story1, name='story1'),
    path('template/', views.contoh_navigasi_bersama, name='contoh_navigasi_bersama'),
    path('extends/', views.contoh_menggunakan_template, name='contoh_menggunakan_template'),
    path('include/', views.contoh_method_include, name='contoh_method_include'),
]

matakuliah/urls.py
from django.urls import path
from . import views

app_name = 'matakuliah'

urlpatterns = [
    path('', views.create_view, name='create_view'),
    path('hasil/', views.list_view, name='list_view'),
    path('hasil/<int:id>/', views.nama_matkul, name='nama_matkul'),
    path('hasil/<int:id>/delete/', views.hapus_matkul, name='hapus_matkul'),
]

story4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('matakuliah/', include('matakuliah.urls')),
    path('kegiatan/', include('story6.urls')),
]

story6/urls.py
from django.urls import path
from . import views

app_name = 'story6'

urlpatterns = [
    path('', views.landing, name='landing'),
    path('hasil/', views.listAcara, name='listAcara'),
    path('hasil/register/<int:index>/', views.register, name='register'),
    path('hasil/<int:index>/', views.hapus_nama, name='hapus_nama'),
]

homepage/models.py
from django.db import models

# Create your models here.

matakuliah/models.py
from django.db import models

# Create your models here.
class DataMatkul(models.Model):
    Nama_Mata_Kuliah = models.CharField(max_length=120)
    Dosen_Pengajar = models.CharField(max_length=120)
    Deskripsi = models.TextField(null=True)
    Semester = models.CharField(max_length=120)
    Ruang = models.CharField(max_length=120)
    Jumlah_SKS = models.IntegerField()

    def __str__(self):
        return self.Nama_Mata_Kuliah

class Tugas(models.Model):
    Nama_Tugas = models.CharField(max_length=120)
    Deadline = models.DateField()
    matakuliah = models.ForeignKey(DataMatkul, on_delete=models.CASCADE)

    class Meta:
        ordering = ['Deadline']

    def __str__(self):
        return self.Nama_Tugas

story6/models.py
from django.db import models

# Create your models here.
class Kegiatan(models.Model):
    Nama_Kegiatan = models.CharField(max_length=120)


class Peserta(models.Model):
    Nama_Peserta = models.CharField(max_length=120)
    Ikut_Kegiatan = models.ForeignKey(Kegiatan, on_delete=models.CASCADE,  null=True, blank=True)

matakuliah/forms.py
from django import forms

from .models import DataMatkul

class DataForm(forms.ModelForm):
    class Meta:
        model = DataMatkul
        fields = [
            'Nama_Mata_Kuliah',
            'Dosen_Pengajar',
            'Deskripsi',
            'Semester',
            'Ruang',
            'Jumlah_SKS',
        ]

story6/forms.py
from django import forms

from .models import Kegiatan, Peserta

class KegiatanForm(forms.ModelForm):
    class Meta:
        model = Kegiatan
        fields = [
            'Nama_Kegiatan',
        ]

class PesertaForm(forms.ModelForm):
    class Meta:
        model = Peserta
        fields = [
            'Nama_Peserta',
        ]

homepage/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'home.html')

def home2(request):
    return render(request, 'home2.html')

def story1(request):
    return render(request, 'story1.html')

def contoh_navigasi_bersama(request):
    return render(request, 'contoh_navigasi_bersama.html')

def contoh_menggunakan_template(request):
    return render(request, 'contoh_menggunakan_template.html')

def contoh_method_include(request):
    return render(request, 'contoh_method_include.html')

matakuliah/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import DataMatkul, Tugas
from .forms import DataForm

# Create your views here.

def create_view(request):
    form = DataForm(request.POST or None)
    if form.is_valid():
        form.save()
        form = DataForm()
    
    context = {
        'form' : form
    }
    return render(request, "landing.html", context)

def list_view(request):
    queryset = DataMatkul.objects.all() #membuat list object

    context = {
        'object_list' : queryset
    }
    return render(request, "list_matkul.html", context)

def hapus_matkul(request, id):
    obj_hapus = get_object_or_404(DataMatkul, id=id) #mengambil nama object

    if request.method == 'POST':
        obj_hapus.delete()
        return redirect('../../')

    context = {
        'object_hapus' : obj_hapus
    }
    return render(request, "hapus_matkul.html", context)

def nama_matkul(request, id):
    obj = get_object_or_404(DataMatkul, id=id)
    obj_tugas = Tugas.objects.all()

    context = {
        'object' : obj,
        'tugas'  : obj_tugas,
    }
    return render(request, "nama_matkul.html", context)

story6/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Kegiatan, Peserta
from .forms import KegiatanForm, PesertaForm

# Create your views here.

def landing(request):
	if request.method == 'POST':
		form = KegiatanForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('/kegiatan/')
	else:
		form = KegiatanForm()
	return render(request, 'homes.html', {'form': form})

def listAcara(request):
    kegiatan = Kegiatan.objects.all()
    peserta = Peserta.objects.all()
    
    return render(request, 'hasilKegiatan.html', {'kegiatan': kegiatan, 'peserta': peserta})

def register(request, index):
	if request.method == 'POST':
		form = PesertaForm(request.POST)
		if form.is_valid():
			pesertaBaru = Peserta(Ikut_Kegiatan=Kegiatan.objects.get(id=index), Nama_Peserta=form.data['Nama_Peserta'])
			pesertaBaru.save()
			return redirect('../../')
	else:
		form = PesertaForm()
	return render(request, 'tambahPeserta.html', {'form': form})

def hapus_nama(request, index):
	obj_temp = get_object_or_404(Peserta, id=index) #mengambilnamaobject
	
	if request.method == 'POST':
		obj_temp.delete()
		return redirect('../')

	context = {
        'object_hapus' : obj_temp
    }
	
	return render(request, "hapus_nama.html", context)

# Create your views here.

homepage/templates/contoh_menggunakan_template.html
{% extends 'contoh_navigasi_bersama.html' %}

{% block content %}
<h1>Hi kak ghifar</h1>
<h1>This page is using same navbar and using method extends from "/template"</h1>
{% endblock %}

homepage/templates/contoh_method_include.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Portofolio</title>
</head>
<body>
    {% include 'contoh_navigasi_bersama.html' %}

    <h1>Hi kak Ghifar</h1>
    <h1>Navbar diatas menggunakan method include dari "/template"</h1>
</body>
</html>

homepage/templates/contoh_navigasi_bersama.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello World :D</title>
    <link rel="stylesheet" type="text/css" href="{% static 'Story3.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</head>



<body>
    <button onclick="topFunction()" id="myBtn" title="Go to top">^</button>

    <nav class="navbar navbar-expand-sm bg-dark navbar-dark justify-content-between">
        <a class="navbar-brand" href="/" style="color: #0EBFAA; margin-left: 1rem;">My CuricullumVitae</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item" style="margin-right: 2rem;">
              <a class="nav-link" href="{% url 'homepage:story1' %}">Story 1</a>
            </li>
            <li class="nav-item" style="margin-right: 2rem;">
              <a class="nav-link" href="#about">About Me</a>
            </li>
            <li class="nav-item" style="margin-right: 2rem;">
              <a class="nav-link" href="#contact">Contact</a>
            </li>    
          </ul>
        </div>  
    </nav>

    {% block content %}
    {% endblock %}

</body>
<script src="{% static 'scroll-up.js' %}"></script>

</html>

homepage/templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello World :D</title>
    <link rel="stylesheet" type="text/css" href="{% static 'Story3.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</head>



<body>
    <button onclick="topFunction()" id="myBtn" title="Go to top">^</button>


    <nav class="navbar navbar-expand-sm bg-dark navbar-dark justify-content-between">
        <a class="navbar-brand" href="" style="color: #0EBFAA; margin-left: 1rem;">My CuricullumVitae</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown" style="margin-right: 2rem;">
              <a class="nav-link dropdown-toggle" data-toggle="dropdown"
                 href="#" role="button" aria-haspopup="true" aria-expanded="false">
                 Progress Story</a>
              <div class="dropdown-menu">
                <h6 class="dropdown-header" style="color: #0EBFAA;">Story 5 & Story 6</h6>
                <a class="dropdown-item" href="/matakuliah">Mata Kuliah</a>
                <a class="dropdown-item" href="/kegiatan">Kegiatan</a>
              </div>
            </li>
            <li class="nav-item" style="margin-right: 2rem;">
              <a class="nav-link" href="{% url 'homepage:story1' %}">Story 1</a>
            </li>
            <li class="nav-item" style="margin-right: 2rem;">
              <a class="nav-link" href="#about">About Me</a>
            </li>
            <li class="nav-item" style="margin-right: 2rem;">
              <a class="nav-link" href="#contact">Contact</a>
            </li>    
          </ul>
        </div>  
    </nav>


    <div class="text-center">
        <h1 style="margin-top: 40vh; margin-bottom: 35vh; font-style: italic;"><span style="color: #0EBFAA">Hola.</span><span style="color: #75D752;"> Hej.</span> Hi.</h1>
    </div>


    <div class="container">
        <div class="row" style="margin-top: 6rem;">
            <div class="col-md-6">
                <h1 style="margin-top: 2rem;">Hello There !</h1>
                <h4 style="margin-top: 4rem;">Welcome to my web, i hope that we can know each other and become a good friend :D</h4>
                <div class="container" style="margin-top: 3rem;">
                    <div class="row">
                      <div class="col-xs-4 col-sm-6 col-md-6" style="background-color: #0EBFAA;">
                        <h6 class="text-center">#CheerfulBoy</h6>
                      </div>
                      <div class="col-xs-4 col-sm-6 col-md-6" style="background-color: #75D752;">
                        <h6 class="text-center">#EntryProgrammer</h6>
                      </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-md-6">
                <div class="container">
                    <img class="img-fluid" src="{% static 'me.jpg' %}" alt="#" style="margin-top: 2rem;">
                </div>
            </div>
        </div>
    </div>


    <div class="container"  id="about">
        <h3 class="text-center" style="margin-top: 4rem; color: #0EBFAA;">My Activity</h3>
    </div>


    <div class="container" style="margin-top: 3rem;">
        <div class="row">
            <div class="col-md-4">
                <div class="container" style="margin-top: 2rem;">
                    <div class="card">
                      <img class="card-img-top" src="{% static 'study.png' %}" alt="Card image" style="width:100%">
                      <div class="card-body">
                        <h4 class="card-title text-center">Study</h4>
                        <p class="card-text">I love studying science about physics, math, and astronomy</p>
                      </div>
                    </div>
                </div>
            </div>    
            <div class="col-md-4"> 
                <div class="container" style="margin-top: 2rem;">
                    <div class="card">
                      <img class="card-img-top" src="{% static 'design.png' %}" alt="Card image" style="width:100%">
                      <div class="card-body">
                        <h4 class="card-title text-center">Design</h4>
                        <p class="card-text">Graphic Design is my passion and my activity when i have spare time.</p>
                      </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4"> 
                <div class="container" style="margin-top: 2rem;">
                    <div class="card">
                      <img class="card-img-top" src="{% static 'coding.png' %}" alt="Card image" style="width:100%">
                      <div class="card-body">
                        <h4 class="card-title text-center">Coding</h4>
                        <p class="card-text">Interested at software engineering, currently mastering java, python, and webdev</p>
                      </div>
                    </div>
                </div>
            </div>    
        </div>
    </div>


    <div class="container">
        <h2 class="text-center" style="margin-top: 4rem; color: #75D752;"><span style="color: #0EBFAA">My Formal</span> Education</h2>
    </div>


    <div class="container" style="margin-top: 3rem;">
        <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="container" style="margin-top: 2rem;">
                        <div class="card">
                          <img class="card-img-top" src="{% static 'smp.jfif' %}" alt="Card image" style="width:100%;">
                          <div class="card-body">
                            <h4 class="card-title text-center">Elementary</h4>
                            <p class="card-text text-center">SDN 03 Wijaya Kusuma</p>
                          </div>
                        </div>
                    </div>
                </div>    
                <div class="col-lg-3 col-md-6"> 
                    <div class="container" style="margin-top: 2rem;">
                        <div class="card">
                          <img class="card-img-top" src="{% static 'sd.jfif' %}" alt="Card image" style="width:100%;">
                          <div class="card-body">
                            <h4 class="card-title text-center">Junior High School</h4>
                            <p class="card-text text-center">SMPN 82 JKT</p>
                          </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6"> 
                    <div class="container" style="margin-top: 2rem;">
                        <div class="card">
                          <img class="card-img-top" src="{% static 'sma.jpg' %}" alt="Card image" style="width:100%;">
                          <div class="card-body">
                            <h4 class="card-title text-center">Senior High School</h4>
                            <p class="card-text text-center">SMAN 29 JKT</p>
                          </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6"> 
                    <div class="container" style="margin-top: 2rem;">
                        <div class="card">
                          <img class="card-img-top" src="{% static 'uai.jpg' %}" alt="Card image" style="width:100%;">
                          <div class="card-body">
                            <h4 class="card-title text-center">Universitas Indonesia</h4>
                            <p class="card-text text-center">Computer Science</p>
                          </div>
                        </div>
                    </div>
                </div>     
            </div>
        </div>

    
    <div class="container">
        <h2 class="text-center" style="margin-top: 4rem; color: #0EBFAA;"><span style="color: #75D752">Few Things</span> About Me.</h2>
    </div>

    <div class="container" style="margin-top: 4rem;">
        <div class="row">
            <div class="col-lg-6 col-md-6">
                <div class="container">
                    <img class="img-fluid" src="{% static 'me2.png' %}" alt="#">
                </div>
            </div>
            <div class="col-lg-6 col-md-6 text-center">
                <h4 style="color: #0EBFAA; margin-top: 2rem;">
                    Simple
                </h4>
                    <h5>I am a guy who strive for simplicity</h5>
                <h4 style="color: #0EBFAA; margin-top: 3rem;">
                    Work Hard - Play Hard
                </h4>
                    <h5>Easily work under pressure and adaptive to others</h5>
                <h4 style="color: #0EBFAA; margin-top: 2rem;">
                    Dicipline
                </h4>
                    <h5>i appreciate punctuary and commitment</h5>
            </div>
        </div>
    </div>

    <div class="container text-center" style="margin-top: 20rem;" id="contact">
        <h2>Get In Touch With Me !</h2>
        <h4 style="margin-top: 4rem;">+62 (81233110190)</h4>
        <h4>Griya BNI Simprug</h4>
        <h4>211 Code 12220</h4>
        <h4 style="margin-top: 3rem;">advis.tasyah@ui.ac.id</h4>
    </div>

    <hr align="center" width="50%">

    <div class="sosmed" style="margin-left: 30vw; margin-top: 5rem; margin-bottom: 4rem;">
        <a href="https://www.linkedin.com/in/advis-tasyah-mulia-5209791a1"><img class="img-fluid" src="{% static 'linkedin.png' %}" alt="" style="max-width: 10%; margin-right: 2vh;"></a>
        <a href="https://twitter.com/Vice_T_M"><img src="{% static 'twitter.png' %}" class="img-fluid" alt="" style="max-width: 10%; margin-right: 2vh;"></a>
        <a href="http://line.me/ti/p/~advis82"><img src="{% static 'line.png' %}" class="img-fluid" alt="" style="max-width: 10%; margin-right: 2vh;"></a>
        <a href="https://api.whatsapp.com/send?phone=6281233110190"><img src="{% static 'whatsap.png' %}" class="img-fluid" alt="" style="max-width: 10%; margin-right: 2vh;"></a>
        <a href="https://www.instagram.com/advis_tm/"><img src="{% static 'instagram.png' %}" class="img-fluid" alt="" style="max-width: 10%; margin-right: 2vh;"></a>
    </div>


    <!-- Button trigger modal -->
    <div class="container d-flex justify-content-center">
      <button type="button" class="btn btn-info" data-toggle="modal" data-target="#Modalchallange">
        See Another Photo
      </button>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="Modalchallange" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">My Gallery</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            
            <!--Disini taro carousel-->
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
              <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
              </ol>
              <div class="carousel-inner">
                <div class="carousel-item active">
                  <img class="d-block w-100" src="{% static 'carousel1.jpg' %}" alt="First slide">
                </div>
                <div class="carousel-item">
                  <img class="d-block w-100" src="{% static 'carousel2.jpg' %}" alt="Second slide">
                </div>
                <div class="carousel-item">
                  <img class="d-block w-100" src="{% static 'me2.png' %}" alt="Third slide">
                </div>
              </div>
              <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>
            <!--End of Carousel-->

          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>


    <div class="container" style="margin-top: 8rem; margin-bottom: 4rem;">
      <a class="btn btn-dark" href="{% url 'homepage:home2' %}">More...</a>
    </div>


</body>
<script src="{% static 'scroll-up.js' %}"></script>

</html>

homepage/templates/home2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</head>
<body>


    <nav class="navbar navbar-expand-sm bg-dark navbar-dark justify-content-between">
        <a class="navbar-brand" href="{% url 'homepage:home' %}" style="color: #0EBFAA; margin-left: 1rem;">My CuricullumVitae</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item" style="margin-right: 2rem;">
              <a class="nav-link" href="{% url 'homepage:home' %}">Home</a>
            </li>
            <li class="nav-item" style="margin-right: 2rem;">
              <a class="nav-link" href="#">coming soon</a>
            </li>
            <li class="nav-item" style="margin-right: 2rem;">
              <a class="nav-link" href="#">coming soon</a>
            </li>    
          </ul>
        </div>  
    </nav>


    <h1 class="text-center" style="margin-top: 4rem;">coming soon</h1>
</body>
</html>

homepage/templates/story1.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>My Portofolio</title>
    <link rel="stylesheet" type="text/css" href="{% static 'Story1.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</head>
<body>
    <header>
        <h1 style="margin-left: 5%;">My Curiculum Vitae</h1>
    </header>
    <div class="Under_Header"></div>
    <center><img src="{% static 'psaf.jpg' %}" alt="" class="image_header"></center>
    <div>
        <div class="desc">
        <h2>Deskripsi Singkat : </h2>
        <p class="deskripsi" align="justify">I am a big fan of good life.
            Saya mencintai dan ingin
            menciptakan kemudahan
            dengan usaha yang lebih
            simpel. Saya ingin menjadi seseorang yang memiliki dampak baik
            terhadap lingkungan saya. Sekarang saya ingin memiliki teman yang baik dan 
            ingin mencapai beberapa target saya kedepan.</p>
        </div>            
        <div class="row">
            <div class="column">
            <img src="{% static 'me.jpg' %}" alt="" class="image_biodata">
            </div>
            <div class="column1">
            <h2>Biodata Saya</h2>    
            <table  class="biodata">
                <tr>
                    <td>Nama</td>
                    <td>: Advis Tasyah Mulia</td>
                </tr>
                <tr>
                    <td>NPM</td>
                    <td>: 1906350673</td>
                </tr>
                <tr>
                    <td>Angkatan</td>
                    <td>: 2019</td>
                </tr>
                <tr>
                    <td>Jurusan</td>
                    <td>: Ilmu Komputer</td>
                </tr>
                <tr>
                    <td>Universitas &nbsp;</td>
                    <td>: Universitas Indonesia</td>
                </tr>
                <tr>
                    <td>Hobi</td>
                    <td>: Futsal, Coding, Film</td>
                </tr>
            </table>
            </div>
        </div>
        <div class="column2">
            <h2>Pendidikan Formal</h2>
            <table class="pendidikan">
                <tr>
                    <td>Universitas Indonesia</td>
                    <td>: 2019 - Sekarang</td>
                </tr>
                <tr>
                    <td>Institut Teknologi Bandung</td>
                    <td>: 2018 - 2019</td>
                </tr>
                <tr>
                    <td>SMA Negeri 29 Jakarta</td>
                    <td>: 2015 - 2018</td>
                </tr>
                <tr>
                    <td>SMP Negeri 82 Jakarta</td>
                    <td>: 2012 - 2015</td>
                </tr>
                <tr>
                    <td>SD Negeri 03 Wijaya Kusuma</td>
                    <td>: 2011 - 2012</td>
                </tr>
                <tr>
                    <td>SDN Karet Tengsin 13 Pagi</td>
                    <td>: 2006 - 2011</td>
                </tr>
            </table>
        </div>
    </div>
    <div class="sosmed">
                <a href="https://twitter.com/Vice_T_M"><img src="{% static 'twitter.png' %}" alt=""></a>
                <a href="http://line.me/ti/p/~advis82"><img src="{% static 'line.png' %}" alt=""></a>
                <a href="https://api.whatsapp.com/send?phone=6281233110190"><img src="{% static 'whatsap.png' %}" alt=""></a>
                <a href="https://www.instagram.com/advis_tm/"><img src="{% static 'instagram.png' %}" alt=""></a>
    </div>

    <div class="container d-flex justify-content-center" style="margin-top: 8rem; margin-bottom: 4rem;">
        <a class="btn btn-dark" href="{% url 'homepage:home' %}">Back to Home</a>
    </div>

    <footer style="background-color: #50d890;">
        <center>
        <p style="padding-top: 7px; font-size: 18px;">Email : advis.tasyah@ui.ac.id</p>
        </center>
    </footer>
</body>
</html>